// performance-test/react-test/src/App.js
import React, { useState } from 'react';
import './App.css';
import CounterButton from './CounterButton';
import CounterDisplay from './CounterDisplay';

function App() {
  let [counter, setCounter] = useState(0);

  const increaseCounter = () => {
    setCounter(counter + 1);
  };

  const decreaseCounter = () => {
    setCounter(counter - 1);
  };

  return (
    <main>
      <CounterButton onClick={increaseCounter} buttonText={'Increase'}></CounterButton>
      <CounterButton onClick={decreaseCounter} buttonText={'Decrease'}></CounterButton>
      <CounterDisplay text={counter}></CounterDisplay>
    </main>
  );
}

export default App;

// performance-test/svelte-test/src/App.svelte
<script>
	import CounterButton from './CounterButton.svelte';
	import CounterDisplay from './CounterDisplay.svelte';
	import { writable } from 'svelte/store';
	const counter = writable(0);
	let counterValue;
	counter.subscribe(c => counterValue = c);

	const increaseCounter = () => {
		counter.update(n => n + 1);
	}

	const decreaseCounter = () => {
		counter.update(n => n - 1);
	}
</script>

<main>
	<CounterButton onClick={increaseCounter} buttonText={'Increase'}></CounterButton>
	<CounterButton onClick={decreaseCounter} buttonText={'Decrease'}></CounterButton>
	<CounterDisplay text={counterValue}></CounterDisplay>
</main>

<style>
	main {
		display: flex;
	}
</style>
